#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
#######################################################################################################
#                                                                                                     #
# generate YourFritz base images with programs missing from stock firmware                            #
#                                                                                                     #
###################################################################################################VER#
#                                                                                                     #
# create_YourFritz_base_image, version 0.6                                                            #
#                                                                                                     #
# This script is a part of the YourFritz project from https://github.com/PeterPawn/YourFritz.         #
#                                                                                                     #
###################################################################################################CPY#
#                                                                                                     #
# Copyright (C) 2016-2019 P.Hämmerlein (peterpawn@yourfritz.de)                                       #
#                                                                                                     #
###################################################################################################LIC#
#                                                                                                     #
# This program is free software; you can redistribute it and/or modify it under the terms of the GNU  #
# General Public License as published by the Free Software Foundation; either version 2 of the        #
# License, or (at your option) any later version.                                                     #
#                                                                                                     #
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without   #
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      #
# General Public License under http://www.gnu.org/licenses/gpl-2.0.html for more details.             #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# constants                                                                                           #
#                                                                                                     #
#######################################################################################################
project="${YF_PROJECT_NAME:-YourFritz}"
marker="base"
image="$project-$marker"
outer_image_mask="\$image-\$proc-\$kernel-\$libc"
yourfritz="$GITHOME/YourFritz"
sign_image="$yourfritz/signimage/sign_image"
check_signed_image="$yourfritz/signimage/check_signed_image"
target_bin="$yourfritz/bin/target"
packages="$GITHOME/yf_bin/packages"
add_license="$yourfritz/LICENSE"
add_info="$packages/README.md"
__bold__="$(printf "\033[1m")"
__undl__="$(printf "\033[4m")"
__red__="$(printf "\033[1m\033[31m")"
__gren__="$(printf "\033[1m\033[32m")"
__yllw__="$(printf "\033[1m\033[33m")"
__blue__="$(printf "\033[1m\033[34m")"
__rset__="$(printf "\033[0m")"
__bold() { printf "$__bold__"; printf -- "$@"; printf "$__rset__"; }
__undl() { printf "$__undl__"; printf -- "$@"; printf "$__rset__"; }
__yourfritz__="$(printf "\033[0m\033[36mY\\033[0m\033[1mour\033[0m\033[36mF\033[0m\033[1mritz\033[0m")"
#######################################################################################################
#                                                                                                     #
# subfunctions                                                                                        #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# usage screen                                                                                        #
#                                                                                                     #
#######################################################################################################
usage()
{
	printf -- "Create a basic image for %s users, containing files not present in stock firmware.\n\n" "$__yourfritz__"
	printf -- "Copyright (C) 2016-2019 P.Hämmerlein (peterpawn@yourfritz.de)\n\n"
	printf -- "Usage:\n\n"
	printf -- "%s <architecture> <processor> <kernel_version> <libc_version>\n\n" "$(__bold "$0")"
	printf -- "Parameters:\n"
	printf -- "%s - processor architecture\n" "$(__bold "architecture")"
	printf -- "- used to locate the the proper binaries from 'yf_bin' sub-directories\n\n"
	printf -- "%s - processor name\n" "$(__bold "processor")"
	printf -- "- used as part of the target image name\n\n"
	printf -- "%s - Linux kernel version\n" "$(__bold "kernel_version")"
	printf -- "- used to locate the proper binaries and as part of the target image name\n\n"
	printf -- "%s - C library version\n" "$(__bold "libc_version")"
	printf -- "- used to locate the proper binaries and as part of the target image name\n\n"
	printf -- "The environment variable '%s' may contain a preset password value for\n" "$(__bold "SIGNIMAGE_PASSWORD")"
	printf -- "the key used to sign the image. If it's present, no question on console is emitted.\n"
	printf -- "The location of the key files is set via 'signimage' sub-project settings.\n"
}
#######################################################################################################
#                                                                                                     #
# files to include into image and their source locations                                              #
#                                                                                                     #
#######################################################################################################
get_files_to_copy()
{
	cat << END_OF_LIST
sbin/mksquashfs=$1/$2/mksquashfs
sbin/unsquashfs=$1/$2/unsquashfs
bin/busybox=$1/$2/busybox
usr/bin/openssl=$1/$2/openssl
usr/bin/decoder=$1/$2/decoder
usr/bin/sign_image=$1/$2/sign_image
usr/bin/image_signing_files.inc=$1/$2/image_signing_files.inc
usr/bin/check_signed_image=$1/$2/check_signed_image
usr/bin/generate_signing_key=$1/$2/generate_signing_key
usr/sbin/privatekeypassword=$1/$2/privatekeypassword
lib/libprivatekeypassword.so=$1/$2/libprivatekeypassword.so
END_OF_LIST
}
#######################################################################################################
#                                                                                                     #
# directories to create and include in the new image                                                  #
#                                                                                                     #
#######################################################################################################
get_directories()
{
	cat << END_OF_LIST
bin
lib
usr
sbin
END_OF_LIST
# additional deeper directories to create, but not to include explicitely with 'tar' command
	[ -n "$1" ] && cat << END_OF_LIST
usr/bin
usr/sbin
END_OF_LIST
}
#######################################################################################################
#                                                                                                     #
# check parameters                                                                                    #
#                                                                                                     #
#######################################################################################################
# architecture
arch="$1"
# processor
proc="$2"
# kernel version
kernel="$3"
# C-library version
libc="$4"
# all arguments present?
if [ -z "$libc" ]; then
	printf "%sMissing arguments.%s\n\n\a" "$__red__" "$__rset__" 1>&2
	usage 1>&2
	exit 1
fi
# check architecture and kernel version
if ! [ -d "$target_bin/$1/$3" ]; then
	printf "%sFiles for architecture '%s' and kernel version '%s' not found.%s\n\n\a" "$__red__" "$__rset__$__bold__$arch$__rset__$__red__" "$__rset__$__bold__$kernel$__rset__$__red__" "$__rset__" 1>&2
	usage 1>&2
	exit 1
fi
# build outer image name
eval outer_image="$outer_image_mask"
#######################################################################################################
#                                                                                                     #
# prepare working directory                                                                           #
#                                                                                                     #
#######################################################################################################
tmp="${TMPDIR:-/tmp}"
tmpdir="$tmp/$1-$2-$3-$4"
stage="$tmpdir/stage"
stage_var="$tmpdir/var"
mkdir -p "$stage_var" 2>/dev/null
get_directories all | \
while read dir; do
	mkdir -p "$stage/$dir" 2>/dev/null
done
#######################################################################################################
#                                                                                                     #
# file staging                                                                                        #
#                                                                                                     #
#######################################################################################################
error=0
while read line; do
	dst="$(expr "$line" : "\([^=]*\).*")"
	src="$(expr "$line" : ".*=\(.*\)")"
	if [ -f "$target_bin/$src" ]; then
		cp -a -L "$target_bin/$src" "$stage/$dst" 2>/dev/null
		sudo chown root:root "$stage/$dst" 2>/dev/null
	else
		printf "%sMissing source file '%s'.%s\n\a" "$__red__" "$__rset__$__bold__$target_bin/$src$__red__" "$__rset__" 1>&2
		error=1
	fi
done < <(get_files_to_copy "$arch" "$kernel")
[ $error -ne 0 ] && exit 1
#######################################################################################################
#                                                                                                     #
# create shell wrapper, which uses the files from base image in front of others from stock firmware   #
#                                                                                                     #
#######################################################################################################
cat > "$stage/bin/$project.sh" << END_OF_WRAPPER
#! /bin/sh
b="/var/$project"
export PATH="\$b/bin:\$b/usr/bin:\$b/sbin:\$b/usr/sbin:\$PATH"
export LD_LIBRARY_PATH="\$b/lib\${LD_LIBRARY_PATH:+\$LD_LIBRARY_PATH:}:/lib"
exec /bin/sh \$@
END_OF_WRAPPER
chmod 555 "$stage/bin/$project.sh" 2>/dev/null
sudo chown root:root "$stage/$project.sh" 2>/dev/null
#######################################################################################################
#                                                                                                     #
# create tarball as image content and include an installation script                                  #
#                                                                                                     #
#######################################################################################################
busybox tar -c -z -f "$stage_var/$image.tar.gz" -C "$stage" $(get_directories)
cat > "$stage_var/install" << END_OF_VAR_INSTALL
#! /bin/sh
basedir="/var/$project"
mkdir -p "\$basedir"
gunzip -c "/var/packet/var/$image.tar.gz" | tar -x -C "\$basedir"
mount -o bind "\$basedir/bin/busybox" /bin/sh
touch "\$basedir/.${marker}_installed"
END_OF_VAR_INSTALL
chmod 555 "$stage_var/install" 2>/dev/null
sudo chown root:root "$stage_var/install" 2>/dev/null
#######################################################################################################
#                                                                                                     #
# add information file and license, if needed                                                         #
#                                                                                                     #
#######################################################################################################
if [ -n "$add_license" ]; then
	cp -a -L "$add_license" "$stage_var"
	chmod 444 "$stage_var/${add_license##*/}" 2>/dev/null
	sudo chown root:root "$stage_var/${add_license##*/}" 2>/dev/null
fi
if [ -n "$add_info" ]; then
	cp -a -L "$add_info" "$stage_var"
	chmod 444 "$stage_var/${add_info##*/}" 2>/dev/null
	sudo chown root:root "$stage_var/${add_info##*/}" 2>/dev/null
fi
#######################################################################################################
#                                                                                                     #
# add description file                                                                                #
#                                                                                                     #
#######################################################################################################
cat > "$stage_var/content.txt" << END_OF_DESC
Project: $project
Path: /var/$project
Component: $marker
Copyright: (C) 2016-2019 Peter Haemmerlein (peterpawn@yourfritz.de)
License: see ${add_license##*/} file
Content:
END_OF_DESC
while read line; do
	dst="$(expr "$line" : "\([^=]*\).*")"
	printf "%s\n" "$dst" >> "$stage_var/content.txt"
done < <(get_files_to_copy . .)
chmod 444 "$stage_var/content.txt" 2>/dev/null
sudo chown root:root "$stage_var/content.txt" 2>/dev/null
#######################################################################################################
#                                                                                                     #
# create unsigned image and sign it with the YourFritz key                                            #
#                                                                                                     #
#######################################################################################################
busybox tar -c -f "$tmpdir/$outer_image.image.unsigned" -C "$tmpdir" ./var
sign_image="$(which sign_image)"
name_prefix="$HOME/$project" YF_SIGNIMAGE_TAR="busybox tar" "$sign_image" "$tmpdir/$outer_image.image.unsigned" "${SIGNIMAGE_PASSWORD}" > "$packages/$outer_image.image"
sign_rc=$?
#######################################################################################################
#                                                                                                     #
# remove temporary files                                                                              #
#                                                                                                     #
#######################################################################################################
rm -r "$tmpdir" 2>/dev/null
#######################################################################################################
#                                                                                                     #
# verify signature, if signing process was successful                                                 #
#                                                                                                     #
#######################################################################################################
[ $sign_rc -eq 0 ] && "$check_signed_image" "$packages/$outer_image.image" -a "$HOME/$project.asc"
#######################################################################################################
#                                                                                                     #
# finish and regular exit                                                                             #
#                                                                                                     #
#######################################################################################################
exit $sign_rc
#######################################################################################################
#                                                                                                     #
# end of script                                                                                       #
#                                                                                                     #
#######################################################################################################
